// 60 comidas con macros
export const meals = [
  { id: 1, name: "Avena con frutas y nueces", calories: 350 },
  { id: 2, name: "Huevos revueltos con espinacas", calories: 300 },
  { id: 3, name: "Pan integral con aguacate", calories: 320 },
  { id: 4, name: "Smoothie de plátano y proteína", calories: 280 },
  { id: 5, name: "Tortilla de claras y champiñones", calories: 200 },
  { id: 6, name: "Yogur griego con miel y almendras", calories: 260 },
  { id: 7, name: "Porridge de quinoa y arándanos", calories: 340 },
  { id: 8, name: "Panqueques avena y plátano", calories: 320 },
  { id: 9, name: "Chia pudding y frutas rojas", calories: 300 },
  { id: 10, name: "Requesón con frutas y nueces", calories: 280 },
  { id: 11, name: "Batido verde de espinaca", calories: 290 },
  { id: 12, name: "Huevos cocidos y tostadas", calories: 330 },
  { id: 13, name: "Pan con pavo y queso fresco", calories: 310 },
  { id: 14, name: "Avena nocturna con chía", calories: 300 },
  { id: 15, name: "Muffins de huevo y verduras", calories: 250 },

  { id: 16, name: "Ensalada de pollo y quinoa", calories: 450 },
  { id: 17, name: "Salmón a la plancha y espárragos", calories: 500 },
  { id: 18, name: "Tacos de pescado integrales", calories: 480 },
  { id: 19, name: "Pasta integral con pollo", calories: 550 },
  { id: 20, name: "Curry de garbanzos y arroz", calories: 600 },
  { id: 21, name: "Ensalada de atún y legumbres", calories: 400 },
  { id: 22, name: "Bowl de ternera y arroz", calories: 530 },
  { id: 23, name: "Wrap de pavo y vegetales", calories: 420 },
  { id: 24, name: "Hamburguesa de lentejas", calories: 520 },
  { id: 25, name: "Salteado de tofu y verduras", calories: 480 },
  { id: 26, name: "Paella de mariscos", calories: 550 },
  { id: 27, name: "Sopa de verduras y pollo", calories: 400 },
  { id: 28, name: "Pollo al curry y brócoli", calories: 500 },
  { id: 29, name: "Ensalada mediterránea de couscous", calories: 450 },
  { id: 30, name: "Filete de cerdo y batata", calories: 550 },

  { id: 31, name: "Tilapia y puré de coliflor", calories: 400 },
  { id: 32, name: "Pavo con zanahorias al vapor", calories: 350 },
  { id: 33, name: "Sopa de lentejas y espinacas", calories: 450 },
  { id: 34, name: "Quinoa con aguacate y pico", calories: 420 },
  { id: 35, name: "Tacos de pollo y maíz", calories: 480 },
  { id: 36, name: "Buddha bowl vegano", calories: 500 },
  { id: 37, name: "Pizza de coliflor y verduras", calories: 450 },
  { id: 38, name: "Hamburguesa de pavo sin pan", calories: 400 },
  { id: 39, name: "Rollitos de lechuga y ternera", calories: 380 },
  { id: 40, name: "Salmón al papillote", calories: 500 },
  { id: 41, name: "Tortilla de espinacas y champi", calories: 350 },
  { id: 42, name: "Curry de verduras con tofu", calories: 450 },
  { id: 43, name: "Pavo al limón y brócoli", calories: 380 },
  { id: 44, name: "Espaguetis de calabacín y pesto", calories: 420 },
  { id: 45, name: "Salteado de gambas y vegetales", calories: 400 },

  { id: 46, name: "Manzana con mantequilla de almendra", calories: 200 },
  { id: 47, name: "Zanahorias baby con hummus", calories: 180 },
  { id: 48, name: "Yogur griego natural", calories: 120 },
  { id: 49, name: "Batido de proteína rápida", calories: 150 },
  { id: 50, name: "Frutos secos mixtos", calories: 250 },
  { id: 51, name: "Barrita de avena casera", calories: 180 },
  { id: 52, name: "Queso cottage con tomate", calories: 130 },
  { id: 53, name: "Pepino con guacamole", calories: 170 },
  { id: 54, name: "Smoothie frutas y espinaca", calories: 200 },
  { id: 55, name: "Apio con crema de cacahuate", calories: 180 },
  { id: 56, name: "Chips de garbanzos al horno", calories: 160 },
  { id: 57, name: "Gelatina sin azúcar y frutas", calories: 90 },
  { id: 58, name: "Crackers integrales y queso", calories: 150 },
  { id: 59, name: "Dátiles rellenos de almendra", calories: 180 },
  { id: 60, name: "Rollitos de pavo y queso", calories: 140 }
];
